// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhg47OSCwAedy76UGmyQ725yApTRDEc1E',
    appId: '1:807888040714:web:3df0696a3c11d8c0c740f3',
    messagingSenderId: '807888040714',
    projectId: 'flutter-encrypt',
    authDomain: 'flutter-encrypt.firebaseapp.com',
    storageBucket: 'flutter-encrypt.appspot.com',
    measurementId: 'G-632PNEP6F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxVPYJ3oUWbOB_Zrn0Oswpi4TcOA7b38',
    appId: '1:807888040714:android:19bca632514014fcc740f3',
    messagingSenderId: '807888040714',
    projectId: 'flutter-encrypt',
    storageBucket: 'flutter-encrypt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNY_9xBM4dKF_xq-6YGvIL9kUY3JunQo',
    appId: '1:807888040714:ios:0051b6c099734032c740f3',
    messagingSenderId: '807888040714',
    projectId: 'flutter-encrypt',
    storageBucket: 'flutter-encrypt.appspot.com',
    iosClientId: '807888040714-id4692f1q2s860gocqt7dq5o8d9tt76p.apps.googleusercontent.com',
    iosBundleId: 'com.example.aesFlutterEncryptDecrypt',
  );
}
